# cross_section_plot.py
# Generated by Copilot per user request: computes X=0.5 vertical cross-sections for base and trays,
# recenters trays to base and draws a matplotlib plot similar to the provided example.

from pathlib import Path
import trimesh
from shapely.ops import unary_union
from shapely.geometry import Polygon, MultiPolygon
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

ASSETS = Path("assets")
BASE_P = ASSETS / "StampBase.stl"
TRAY1_P = ASSETS / "Tray1Slot.stl"
TRAY2_P = ASSETS / "Tray2Slot.stl"


def load_mesh(p: Path):
    if not p.exists():
        raise FileNotFoundError(f"Missing asset: {p}")
    return trimesh.load_mesh(str(p), force='mesh')


def compute_x_section(mesh, ratio=0.5, try_offsets=3, offset_step=0.005):
    """
    Attempt vertical X-axis slice at center (ratio=0.5).
    If section is None, try nearby offsets (left/right) to find a non-empty slice.
    Returns a shapely geometry (Polygon or MultiPolygon) or None.
    """
    bounds = mesh.bounds
    minb = bounds[0]
    maxb = bounds[1]
    base_x = minb[0] + ratio * (maxb[0] - minb[0])
    normals = (1.0, 0.0, 0.0)

    # try offsets around base_x
    offsets = [0.0]
    for i in range(1, try_offsets + 1):
        offsets.append(i * offset_step)
        offsets.append(-i * offset_step)

    polys = []
    for off in offsets:
        origin = mesh.centroid.copy()
        origin[0] = base_x + off
        section = mesh.section(plane_origin=origin, plane_normal=normals)
        if section is None:
            continue
        p2 = section.to_planar()
        # prefer polygons_full, fall back to polygons
        raw_polys = getattr(p2, "polygons_full", None) or getattr(p2, "polygons", None)
        if raw_polys:
            try:
                geom = unary_union(raw_polys)
                # ensure we have Polygon/MultiPolygon
                if isinstance(geom, (Polygon, MultiPolygon)):
                    return geom
            except Exception:
                pass
        # else try constructing from paths
        paths = getattr(p2, "paths", None)
        if paths:
            for path in paths:
                coords = getattr(path, "vertices", None)
                if coords is not None and len(coords) >= 3:
                    try:
                        polys.append(Polygon(coords))
                    except Exception:
                        pass
            if polys:
                return unary_union(polys)
    return None


def silhouette(mesh):
    # fallback: top-down silhouette using convex hull of XY vertices
    pts = mesh.vertices[:, :2]
    try:
        from shapely.geometry import MultiPoint
        hull = MultiPoint(list(map(tuple, pts))).convex_hull
        return hull
    except Exception:
        return None


def geom_to_patches(geom, facecolor="#bda87c", edgecolor="#000000", linewidth=1.2):
    patches = []
    if geom is None:
        return patches
    if isinstance(geom, Polygon):
        polys = [geom]
    else:
        polys = [p for p in geom.geoms]
    for poly in polys:
        exterior = list(poly.exterior.coords)
        patch = mpatches.Polygon(exterior, closed=True,
                                facecolor=facecolor, edgecolor=edgecolor,
                                linewidth=linewidth, zorder=3)
        patches.append(patch)
        for hole in poly.interiors:
            hole_coords = list(hole.coords)
            hole_patch = mpatches.Polygon(hole_coords, closed=True,
                                          facecolor="white", edgecolor=edgecolor,
                                          linewidth=linewidth, zorder=4)
            patches.append(hole_patch)
    return patches


def draw_cross_sections(base_geom, tray_geoms, out="cross_section_result.png"):
    # unify bounds
    all_geoms = [g for g in ([base_geom] + tray_geoms) if g is not None]
    union = unary_union(all_geoms)
    minx, miny, maxx, maxy = union.bounds
    margin_x = (maxx - minx) * 0.06
    margin_y = (maxy - miny) * 0.06
    figw = 10
    figh = max(3, figw * ((maxy - miny + 2 * margin_y) / (maxx - minx + 2 * margin_x)))
    fig, ax = plt.subplots(figsize=(figw, figh))
    ax.set_facecolor("#fff0e6")
    plt.xlim(minx - margin_x, maxx + margin_x)
    plt.ylim(miny - margin_y, maxy + margin_y)
    ax.set_aspect('equal', adjustable='box')
    ax.axis('off')

    # draw hatched frame rectangle behind everything
    frame = mpatches.Rectangle((minx - margin_x, miny - margin_y),
                               (maxx - minx) + 2 * margin_x, (maxy - miny) + 2 * margin_y,
                               facecolor="#ffece6", edgecolor="#000000", linewidth=1.6,
                               hatch='////', zorder=0)
    ax.add_patch(frame)

    # draw trays (under base): lighter fills
    tray_color = "#d6b98d"
    for g in tray_geoms:
        if g is None:
            continue
        for p in geom_to_patches(g, facecolor=tray_color, edgecolor="#333333", linewidth=1.0):
            p.set_zorder(1)
            ax.add_patch(p)

    # draw base ON TOP with stronger edge and slightly different color
    if base_geom is not None:
        base_patches = geom_to_patches(base_geom, facecolor="#bda87c", edgecolor="#000000", linewidth=1.6)
        for p in base_patches:
            p.set_zorder(5)
            ax.add_patch(p)

    plt.tight_layout()
    plt.savefig(out, dpi=200)
    print(f"Saved {out}")
    plt.show()


def main():
    base_mesh = load_mesh(BASE_P)
    tray1_mesh = load_mesh(TRAY1_P)
    tray2_mesh = load_mesh(TRAY2_P)

    base_sec = compute_x_section(base_mesh, ratio=0.5)
    if base_sec is None:
        print("Base: X=0.5 section missing, using silhouette fallback")
        base_sec = silhouette(base_mesh)

    tray1_sec = compute_x_section(tray1_mesh, ratio=0.5)
    if tray1_sec is None:
        print("Tray1: X=0.5 section missing, using silhouette fallback")
        tray1_sec = silhouette(tray1_mesh)

    tray2_sec = compute_x_section(tray2_mesh, ratio=0.5)
    if tray2_sec is None:
        print("Tray2: X=0.5 section missing, using silhouette fallback")
        tray2_sec = silhouette(tray2_mesh)

    # recenter trays to base centroid for display
    try:
        bx, by = base_sec.centroid.x, base_sec.centroid.y
        def recenter(g):
            if g is None:
                return None
            gx, gy = g.centroid.x, g.centroid.y
            return from_shapely_translate(g, bx - gx, by - gy)
    except Exception:
        recenter = lambda g: g

    # shapely translate helper
    from shapely.affinity import translate as from_shapely_translate
    tray1_sec = recenter(tray1_sec)
    tray2_sec = recenter(tray2_sec)

    draw_cross_sections(base_sec, [tray1_sec, tray2_sec], out="cross_section_result.png")

if __name__ == "__main__":
    main()
